'use strict';

const PROTOCOL_VERSION = 'agent-bridge.v1';
const PROTOCOL_VERSION_V2 = 'agent-bridge.v2';

const RequestType = Object.freeze({
  HELLO: 'hello',
  PING: 'bridge.ping',
  APP_PING: 'ping',
  SERVER_INFO_GET: 'server.info.get',
  CAPABILITIES_GET: 'capabilities.get',
  PROVIDER_CATALOG: 'provider.catalog',
  PROVIDER_CATALOG_REFRESH: 'provider.catalog.refresh',
  AGENT_LIST: 'agent.list',
  AGENT_CREATE: 'agent.create',
  AGENT_RUN: 'agent.run',
  AGENT_STATUS: 'agent.status',
  AGENT_ATTACH: 'agent.attach',
  AGENT_SEND: 'agent.send',
  AGENT_STOP: 'agent.stop',
  AGENT_RESUME: 'agent.resume',
  AGENT_DELETE: 'agent.delete',
  AGENT_UPDATE: 'agent.update',
  AGENT_MODE_SET: 'agent.mode.set',
  AGENT_MODEL_SET: 'agent.model.set',
  AGENT_ARCHIVE: 'agent.archive',
  AGENT_ATTENTION_CLEAR: 'agent.attention.clear',
  AGENT_FORK: 'agent.fork',
  AGENT_DETACH: 'agent.detach',
  CHECKPOINT_LIST: 'checkpoint.list',
  CHECKPOINT_CREATE: 'checkpoint.create',
  CHECKPOINT_RESTORE: 'checkpoint.restore',
  TIMELINE_FETCH: 'timeline.fetch',
  TIMELINE_ACK: 'timeline.ack',
  WORKSPACE_REGISTRY_LIST: 'workspace.registry.list',
  WORKSPACE_REGISTRY_CREATE: 'workspace.registry.create',
  WORKSPACE_REGISTRY_IMPORT: 'workspace.registry.import',
  WORKSPACE_REGISTRY_UPSERT: 'workspace.registry.upsert',
  WORKSPACE_REGISTRY_ARCHIVE: 'workspace.registry.archive',
  WORKSPACE_REGISTRY_OPEN: 'workspace.registry.open',
  WORKSPACE_REGISTRY_SUGGESTIONS: 'workspace.registry.suggestions',
  WORKSPACE_REGISTRY_DOCTOR: 'workspace.registry.doctor',
  PROJECT_REGISTRY_LIST: 'project.registry.list',
  TERMINAL_LIST: 'terminal.list',
  TERMINAL_CREATE: 'terminal.create',
  TERMINAL_SUBSCRIBE: 'terminal.subscribe',
  TERMINAL_UNSUBSCRIBE: 'terminal.unsubscribe',
  TERMINAL_CAPTURE: 'terminal.capture',
  TERMINAL_KILL: 'terminal.kill',
  TERMINAL_RENAME: 'terminal.rename',
  TERMINAL_HOOK_INSTALL: 'terminal.hook.install',
  TERMINAL_HOOK_STATUS: 'terminal.hook.status',
  FILE_TRANSFER_DOWNLOAD: 'file.transfer.download',
  FILE_TRANSFER_UPLOAD: 'file.transfer.upload',
  FILE_TRANSFER_CANCEL: 'file.transfer.cancel',
  PROVIDER_PROFILE_LIST: 'provider.profile.list',
  PROVIDER_PROFILE_UPSERT: 'provider.profile.upsert',
  PROVIDER_PROFILE_DELETE: 'provider.profile.delete',
  PROVIDER_PROFILE_TEST: 'provider.profile.test',
  PROVIDER_ACP_DISCOVER: 'provider.acp.discover',
  PROVIDER_ACP_IMPORT: 'provider.acp.import',
  PROVIDER_DIRECTORY_LIST: 'provider.directory.list',
  PROVIDER_DIRECTORY_REFRESH: 'provider.directory.refresh',
  PROVIDER_DIRECTORY_INSTALL: 'provider.directory.install',
  PROVIDER_DIRECTORY_STATUS: 'provider.directory.status',
  PROVIDER_DIRECTORY_ROLLBACK: 'provider.directory.rollback',
  PROVIDER_DIRECTORY_REMOVE: 'provider.directory.remove',
  SESSION_CREATE: 'session.create',
  SESSION_LIST: 'session.list',
  SESSION_MESSAGES: 'session.messages',
  SESSION_REVERT: 'session.revert',
  SESSION_ABORT: 'session.abort',
  MESSAGE_SEND: 'message.send',
  MESSAGE_QUEUE_LIST: 'message.queue.list',
  MESSAGE_QUEUE_CANCEL: 'message.queue.cancel',
  MESSAGE_QUEUE_RETRY: 'message.queue.retry',
  USAGE_SUMMARY_GET: 'usage.summary.get',
  USAGE_EVENTS_LIST: 'usage.events.list',
  USAGE_BUDGET_GET: 'usage.budget.get',
  USAGE_BUDGET_SET: 'usage.budget.set',
  PROVIDER_USAGE_LIST: 'provider.usage.list',
  METADATA_GENERATE: 'metadata.generate',
  METADATA_GENERATE_CANCEL: 'metadata.generate.cancel',
  DIAGNOSTICS_EXPORT: 'diagnostics.export',
  RELAY_STATUS: 'relay.status',
  RELAY_PAIRING_START: 'relay.pairing.start',
  RELAY_PAIRING_CANCEL: 'relay.pairing.cancel',
  RELAY_CONNECT: 'relay.connect',
  RELAY_DISCONNECT: 'relay.disconnect',
  RELAY_DEVICE_LIST: 'relay.device.list',
  RELAY_DEVICE_REVOKE: 'relay.device.revoke',
  RELAY_IDENTITY_ROTATE: 'relay.identity.rotate',
  SCHEDULE_STATUS: 'schedule.status',
  SCHEDULE_LIST: 'schedule.list',
  SCHEDULE_GET: 'schedule.get',
  SCHEDULE_CREATE: 'schedule.create',
  SCHEDULE_UPDATE: 'schedule.update',
  SCHEDULE_ENABLE: 'schedule.enable',
  SCHEDULE_DISABLE: 'schedule.disable',
  SCHEDULE_RUN_NOW: 'schedule.run-now',
  SCHEDULE_HISTORY: 'schedule.history',
  SCHEDULE_REMOVE: 'schedule.remove',
  LOOP_STATUS: 'loop.status',
  LOOP_LIST: 'loop.list',
  LOOP_GET: 'loop.get',
  LOOP_CREATE: 'loop.create',
  LOOP_UPDATE: 'loop.update',
  LOOP_START: 'loop.start',
  LOOP_PAUSE: 'loop.pause',
  LOOP_RESUME: 'loop.resume',
  LOOP_STOP: 'loop.stop',
  LOOP_TAKEOVER: 'loop.takeover',
  LOOP_ROUNDS: 'loop.rounds',
  LOOP_REMOVE: 'loop.remove',
  CHAT_ROOM_STATUS: 'chat.room.status',
  CHAT_ROOM_LIST: 'chat.room.list',
  CHAT_ROOM_GET: 'chat.room.get',
  CHAT_ROOM_CREATE: 'chat.room.create',
  CHAT_ROOM_UPDATE: 'chat.room.update',
  CHAT_ROOM_ARCHIVE: 'chat.room.archive',
  CHAT_ROOM_MEMBER_ADD: 'chat.room.member.add',
  CHAT_ROOM_MEMBER_UPDATE: 'chat.room.member.update',
  CHAT_ROOM_MEMBER_REMOVE: 'chat.room.member.remove',
  CHAT_ROOM_MESSAGE_POST: 'chat.room.message.post',
  CHAT_ROOM_MESSAGE_LIST: 'chat.room.message.list',
  CHAT_ROOM_ACK: 'chat.room.ack',
  VOICE_STATUS: 'voice.status',
  VOICE_SESSION_START: 'voice.session.start',
  VOICE_SESSION_CHUNK: 'voice.session.chunk',
  VOICE_SESSION_FINISH: 'voice.session.finish',
  VOICE_SESSION_CANCEL: 'voice.session.cancel',
  VOICE_TTS_SPEAK: 'voice.tts.speak',
  VOICE_TTS_STOP: 'voice.tts.stop',
  WORKSPACE_SERVICE_LIST: 'workspace.service.list',
  WORKSPACE_SERVICE_UPSERT: 'workspace.service.upsert',
  WORKSPACE_SERVICE_STATUS: 'workspace.service.status',
  WORKSPACE_SERVICE_HEALTH: 'workspace.service.health',
  WORKSPACE_SERVICE_OPEN: 'workspace.service.open',
  WORKSPACE_SERVICE_START: 'workspace.service.start',
  WORKSPACE_SERVICE_STOP: 'workspace.service.stop',
  WORKSPACE_SERVICE_LOGS: 'workspace.service.logs',
  WORKSPACE_SERVICE_REMOVE: 'workspace.service.remove',
  BROWSER_HOST_REGISTER: 'browser.host.register',
  BROWSER_HOST_UNREGISTER: 'browser.host.unregister',
  BROWSER_HOST_RESULT: 'browser.host.result',
  BROWSER_HOST_LIST: 'browser.host.list',
  BROWSER_INSTANCE_LIST: 'browser.instance.list',
  BROWSER_INSTANCE_CREATE: 'browser.instance.create',
  BROWSER_INSTANCE_CLOSE: 'browser.instance.close',
  BROWSER_PAGE_LIST: 'browser.page.list',
  BROWSER_PAGE_CREATE: 'browser.page.create',
  BROWSER_PAGE_CLOSE: 'browser.page.close',
  BROWSER_PAGE_NAVIGATE: 'browser.page.navigate',
  BROWSER_PAGE_SNAPSHOT: 'browser.page.snapshot',
  BROWSER_PAGE_SCREENSHOT: 'browser.page.screenshot',
  BROWSER_PAGE_LOGS: 'browser.page.logs',
  BROWSER_PAGE_WAIT: 'browser.page.wait',
  BROWSER_PAGE_ACTION: 'browser.page.action',
  BROWSER_DOWNLOAD_LIST: 'browser.download.list',
  BROWSER_PERMISSION_GET: 'browser.permission.get',
  BROWSER_PERMISSION_SET: 'browser.permission.set',
  PREVIEW_GET: 'preview.get',
  PERMISSION_LIST: 'permission.list',
  PERMISSION_RESPOND: 'permission.respond',
  REQUEST_RESPOND: 'request.respond',
  PLAN_RESPOND: 'plan.respond',
  OPENCODE_REQUEST: 'opencode.request',
  WORKSPACE_CHANGES_GET: 'workspace.changes.get',
  WORKSPACE_DIFF_GET: 'workspace.diff.get',
  WORKSPACE_FILES_LIST: 'workspace.files.list',
  WORKSPACE_FILE_GET: 'workspace.file.get',
  WORKSPACE_FILE_DOWNLOAD: 'workspace.file.download',
  ATTACHMENT_FILE_DOWNLOAD: 'attachment.file.download',
  WORKSPACE_GIT_STAGE: 'workspace.git.stage',
  WORKSPACE_GIT_UNSTAGE: 'workspace.git.unstage',
  WORKSPACE_GIT_DISCARD: 'workspace.git.discard',
  WORKSPACE_GIT_COMMIT: 'workspace.git.commit',
  WORKSPACE_GIT_PULL: 'workspace.git.pull',
  WORKSPACE_GIT_PUSH: 'workspace.git.push',
  WORKSPACE_GIT_BRANCH: 'workspace.git.branch',
  WORKSPACE_GIT_STASH: 'workspace.git.stash',
  WORKSPACE_GIT_MERGE: 'workspace.git.merge',
  WORKSPACE_GIT_SUBSCRIBE: 'workspace.git.subscribe',
  WORKTREE_LIST: 'worktree.list',
  WORKTREE_CREATE: 'worktree.create',
  WORKTREE_ARCHIVE: 'worktree.archive',
  GITHUB_PR_CREATE: 'github.pr.create',
  GITHUB_PR_LIST: 'github.pr.list',
  GITHUB_PR_UPDATE: 'github.pr.update',
  GITHUB_PR_REVIEWERS_UPDATE: 'github.pr.reviewers.update',
  GITHUB_PR_LABELS_UPDATE: 'github.pr.labels.update',
  GITHUB_PR_MERGE: 'github.pr.merge',
  GITHUB_PR_STATUS: 'github.pr.status',
  GITHUB_CHECKS_LIST: 'github.checks.list',
  GITHUB_ISSUE_SEARCH: 'github.issue.search',
  GITHUB_ISSUE_ATTACHMENT_LIST: 'github.issue.attachment.list',
  GITHUB_AUTH_DEVICE_START: 'github.auth.device.start',
  GITHUB_AUTH_DEVICE_POLL: 'github.auth.device.poll',
  GITHUB_AUTH_STATUS: 'github.auth.status',
  GITHUB_AUTH_LOGOUT: 'github.auth.logout',
  GITHUB_ACCOUNT_LIST: 'github.account.list',
  GITHUB_BINDING_GET: 'github.binding.get',
  GITHUB_BINDING_SET: 'github.binding.set',
  GITHUB_WATCH_START: 'github.watch.start',
  GITHUB_WATCH_STOP: 'github.watch.stop',
  GITHUB_ATTACHMENT_PREVIEW: 'github.attachment.preview',
  GITHUB_ATTACHMENT_UPLOAD: 'github.attachment.upload',
  MCP_SERVER_START: 'mcp.server.start',
  MCP_SERVER_STOP: 'mcp.server.stop',
  MCP_TOOLS_LIST: 'mcp.tools.list',
  NOTIFICATION_LIST: 'notification.list',
  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_ACTION: 'notification.action',
  NOTIFICATION_PRUNE: 'notification.prune',
  NOTIFICATION_PUSH_STATUS: 'notification.push.status',
  NOTIFICATION_PUSH_REGISTER: 'notification.push.register',
  NOTIFICATION_PUSH_UNREGISTER: 'notification.push.unregister',
  DAEMON_STATUS: 'daemon.status',
  DAEMON_HEALTH: 'daemon.health',
  DAEMON_START: 'daemon.start',
  DAEMON_STOP: 'daemon.stop',
  DAEMON_RESTART: 'daemon.restart',
  DAEMON_LOGS: 'daemon.logs',
  DAEMON_AUTOSTART_STATUS: 'daemon.autostart.status',
  DAEMON_AUTOSTART_PREVIEW: 'daemon.autostart.preview',
  DAEMON_AUTOSTART_SET: 'daemon.autostart.set',
  DAEMON_AUTOSTART_INSTALL: 'daemon.autostart.install',
  DAEMON_AUTOSTART_UNINSTALL: 'daemon.autostart.uninstall',
  DAEMON_UPDATE_STATUS: 'daemon.update.status',
  DAEMON_UPDATE_CHECK: 'daemon.update.check',
  DAEMON_UPDATE_PREVIEW: 'daemon.update.preview',
  DAEMON_UPDATE_INSTALL: 'daemon.update.install',
  DAEMON_UPDATE_ROLLBACK: 'daemon.update.rollback',
  DAEMON_CONFIG_STATUS: 'daemon.config.status',
  DAEMON_CONFIG_FETCH: 'daemon.config.fetch',
  DAEMON_CONFIG_VALIDATE: 'daemon.config.validate',
  DAEMON_CONFIG_PREVIEW: 'daemon.config.preview',
  DAEMON_CONFIG_APPLY: 'daemon.config.apply',
  DAEMON_CONFIG_ROLLBACK: 'daemon.config.rollback',
  DAEMON_INSTANCE_STATUS: 'daemon.instance.status',
  SECURITY_AUDIT_LIST: 'security.audit.list',
  SECURITY_TLS_STATUS: 'security.tls.status',
  SECURITY_TLS_SET: 'security.tls.set',
  SECURITY_HOSTS_STATUS: 'security.hosts.status',
  SECURITY_HOSTS_SET: 'security.hosts.set',
  SECURITY_TOKEN_STATUS: 'security.token.status',
  SECURITY_TOKEN_ROTATE: 'security.token.rotate',
  SECURITY_AUTH_STATUS: 'security.auth.status',
  SECURITY_AUTH_SET: 'security.auth.set',
  SECURITY_DEVICE_LIST: 'security.device.list',
  SECURITY_DEVICE_TRUST: 'security.device.trust',
  SECURITY_DEVICE_REVOKE: 'security.device.revoke'
});

const EventType = Object.freeze({
  BRIDGE_CONNECTED: 'bridge.connected',
  SERVER_INFO: 'server.info',
  AGENT_CREATED: 'agent.created',
  AGENT_UPDATED: 'agent.updated',
  AGENT_DELETED: 'agent.deleted',
  AGENT_RELATIONSHIP_UPDATED: 'agent.relationship.updated',
  AGENT_TIMELINE_UPDATED: 'agent.timeline.updated',
  CHECKPOINT_UPDATED: 'checkpoint.updated',
  PROVIDER_CATALOG_UPDATED: 'provider.catalog.updated',
  PROVIDER_PROFILE_UPDATED: 'provider.profile.updated',
  PROVIDER_DIRECTORY_UPDATED: 'provider.directory.updated',
  WORKSPACE_REGISTRY_UPDATED: 'workspace.registry.updated',
  WORKTREE_UPDATED: 'worktree.updated',
  TERMINAL_UPDATED: 'terminal.updated',
  TERMINAL_HOOK_UPDATED: 'terminal.hook.updated',
  TERMINAL_CAPTURE_PERSISTED: 'terminal.capture.persisted',
  TERMINAL_STREAM_EXIT: 'terminal.stream.exit',
  TERMINAL_ATTENTION: 'terminal.attention',
  FILE_TRANSFER_PROGRESS: 'file.transfer.progress',
  FILE_TRANSFER_COMPLETED: 'file.transfer.completed',
  FILE_TRANSFER_FAILED: 'file.transfer.failed',
  SESSION_CREATED: 'session.created',
  SESSION_UPDATED: 'session.updated',
  SESSION_MESSAGES: 'session.messages',
  MESSAGE_DELTA: 'message.delta',
  MESSAGE_COMPLETED: 'message.completed',
  MESSAGE_QUEUE_UPDATED: 'message.queue.updated',
  USAGE_UPDATED: 'usage.updated',
  USAGE_BUDGET_WARNING: 'usage.budget.warning',
  RELAY_UPDATED: 'relay.updated',
  RELAY_DEVICE_UPDATED: 'relay.device.updated',
  SCHEDULE_UPDATED: 'schedule.updated',
  SCHEDULE_RUN_UPDATED: 'schedule.run.updated',
  LOOP_UPDATED: 'loop.updated',
  LOOP_ROUND_UPDATED: 'loop.round.updated',
  CHAT_ROOM_UPDATED: 'chat.room.updated',
  CHAT_ROOM_MESSAGE_CREATED: 'chat.room.message.created',
  CHAT_ROOM_ACK_UPDATED: 'chat.room.ack.updated',
  VOICE_TRANSCRIPT_PARTIAL: 'voice.transcript.partial',
  VOICE_TRANSCRIPT_FINAL: 'voice.transcript.final',
  VOICE_VAD_CHANGED: 'voice.vad.changed',
  VOICE_TTS_UPDATED: 'voice.tts.updated',
  VOICE_SESSION_UPDATED: 'voice.session.updated',
  WORKSPACE_SERVICE_UPDATED: 'workspace.service.updated',
  BROWSER_HOST_COMMAND: 'browser.host.command',
  BROWSER_UPDATED: 'browser.updated',
  TOOL_STARTED: 'tool.started',
  TOOL_OUTPUT: 'tool.output',
  TOOL_COMPLETED: 'tool.completed',
  PERMISSION_REQUESTED: 'permission.requested',
  QUESTION_REQUESTED: 'question.requested',
  PLAN_REQUESTED: 'plan.requested',
  PLAN_UPDATED: 'plan.updated',
  TODO_UPDATED: 'todo.updated',
  OPENCODE_EVENT: 'opencode.event',
  PREVIEW_UPDATED: 'preview.updated',
  WORKSPACE_CHANGES_UPDATED: 'workspace.changes.updated',
  WORKSPACE_DIFF_SUBSCRIPTION_UPDATED: 'workspace.diff.subscription.updated',
  WORKSPACE_FILES_UPDATED: 'workspace.files.updated',
  FILE_DOWNLOAD_READY: 'file.download.ready',
  GITHUB_PR_UPDATED: 'github.pr.updated',
  GITHUB_CHECKS_UPDATED: 'github.checks.updated',
  GITHUB_AUTH_UPDATED: 'github.auth.updated',
  GITHUB_BINDING_UPDATED: 'github.binding.updated',
  NOTIFICATION_CREATED: 'notification.created',
  NOTIFICATION_UPDATED: 'notification.updated',
  NOTIFICATION_ACTION: 'notification.action',
  NOTIFICATION_PUSH_UPDATED: 'notification.push.updated',
  DAEMON_HEALTH_UPDATED: 'daemon.health.updated',
  DAEMON_UPDATE_UPDATED: 'daemon.update.updated',
  DAEMON_CONFIG_UPDATED: 'daemon.config.updated',
  SECURITY_WARNING: 'security.warning',
  ERROR: 'error'
});

function makeResponse(id, payload) {
  return {
    id,
    type: 'response',
    ok: true,
    payload: payload || {},
    createdAt: Date.now()
  };
}

function makeErrorResponse(id, code, message) {
  return {
    id: id || '',
    type: 'response',
    ok: false,
    error: {
      code,
      message,
      retryable: false,
      details: {}
    },
    createdAt: Date.now()
  };
}

function makeEvent(event, sessionId, payload) {
  return {
    type: 'event',
    event,
    sessionId: sessionId || '',
    payload: payload || {},
    createdAt: Date.now()
  };
}

function parseClientMessage(text) {
  try {
    const parsed = JSON.parse(text);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return { ok: false, error: 'Message must be a JSON object' };
    }
    if (typeof parsed.type !== 'string' || parsed.type.length === 0) {
      return { ok: false, error: 'Message type is required' };
    }
    return { ok: true, value: parsed };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
}

function readString(source, key, fallbackValue) {
  if (!source || typeof source !== 'object') {
    return fallbackValue;
  }
  const value = source[key];
  if (typeof value === 'string') {
    return value;
  }
  return fallbackValue;
}

function readNumber(source, key, fallbackValue) {
  if (!source || typeof source !== 'object') {
    return fallbackValue;
  }
  const value = source[key];
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }
  return fallbackValue;
}

module.exports = {
  PROTOCOL_VERSION,
  PROTOCOL_VERSION_V2,
  RequestType,
  EventType,
  makeResponse,
  makeErrorResponse,
  makeEvent,
  parseClientMessage,
  readString,
  readNumber
};
